# frozen_string_literal: true

# Code generated by gen/generate.rb — DO NOT EDIT.
# Re-run `ruby gen/generate.rb` after updating the gateway OpenAPI schema.
#
# Source: rail0-gateway/docs/openapi.json — components.schemas.DisputeOpenReason,
# DisputeCloseReason and DisputeSystemCloseReason (enum, x-enum-descriptions and
# x-enum-bytes32, aligned by index).

module Rail0
  # The gateway's dispute-reason dictionary. On-chain a dispute reason is a bytes32,
  # keccak256("rail0.dispute.<code>"); the dispute prepares take either the code or
  # exactly that bytes32, and refuse anything else 422 unknown_dispute_reason. A
  # dispute read back carries `reason_code`/`reason_description` (and the close_
  # counterparts) already decoded by the gateway; these constants are for building a
  # picker, validating input before a round trip, or decoding a raw bytes32.
  module DisputeReasons
    # One dictionary entry: the code the API speaks, its English description and the
    # bytes32 the contract stores.
    Reason = Struct.new(:code, :description, :bytes32, keyword_init: true)

    # What the gateway reports as the description of a bytes32 outside the dictionary.
    UNRECOGNISED_DESCRIPTION = "Unrecognised reason"

    # Reasons a payer may open a dispute with (Payments#dispute_prepare).
    OPEN = [
      Reason.new(
        code: "not_received",
        description: "Goods or service not received",
        bytes32: "0x8b8e446d6f906b670526e73bf5502f1db64b2150c42360febf9dec0d075a28f9"
      ).freeze,
      Reason.new(
        code: "not_as_described",
        description: "Not as described, or not what was ordered",
        bytes32: "0xd7ac93eb8a6f78f2398d7131c7d34ac3cc667872ccd86f9acb2acf0b1c1ce68d"
      ).freeze,
      Reason.new(
        code: "damaged_or_defective",
        description: "Arrived damaged or defective",
        bytes32: "0xedaf2417cca94f10d7611552c2c3a9a9fcf7aeecb58bc213c9290ea0c7e58f3a"
      ).freeze,
      Reason.new(
        code: "duplicate",
        description: "Charged twice for the same purchase",
        bytes32: "0x21d2ae9aec01aa72dfe968be0b24b311d8f9b26491ad3f5122ee6bce9c0da16f"
      ).freeze,
      Reason.new(
        code: "incorrect_amount",
        description: "Amount differs from what was agreed",
        bytes32: "0x668fab4989c1fca438fa96c57778b3a0f1a46766bfbce495d8704fd1b0aa6ab6"
      ).freeze,
      Reason.new(
        code: "cancelled",
        description: "Order or subscription cancelled but still charged",
        bytes32: "0xf0e563be58fdee0107cd6907d4040a859af4753a93cafa838e374a1b6c6880d4"
      ).freeze,
      Reason.new(
        code: "refund_not_received",
        description: "A refund promised by the merchant never arrived",
        bytes32: "0x654f13ad1cef4e3e1c74161e98f531e730883aa4d14855ee35546f5485de13ce"
      ).freeze,
      Reason.new(
        code: "unauthorized",
        description: "Payment not recognised (e.g. a compromised wallet)",
        bytes32: "0x5a8e87ece389352e3ad16b9cc84ecb7348115546c041e079f18011d158934079"
      ).freeze,
      Reason.new(
        code: "other",
        description: "Other reason, detailed off-chain",
        bytes32: "0x0c507c226b608fa1f2920608f9c8baf135357fe717c6cd9ac355ae6451b63667"
      ).freeze
    ].freeze

    # Reasons a payer may close a dispute with (Payments#close_dispute_prepare).
    CLOSE = [
      Reason.new(
        code: "resolved_with_merchant",
        description: "Resolved with the merchant off-chain",
        bytes32: "0x37b092a939a58d27e17848d569e5abb446933c05d90edb8f2ad69caae8b9416a"
      ).freeze,
      Reason.new(
        code: "withdrawn",
        description: "Withdrawn by the buyer (a mistake, or changed their mind)",
        bytes32: "0x304c3ad3e1c95131e0e666568cb55d269a5382b83f18dcd07137626b07de4d91"
      ).freeze,
      Reason.new(
        code: "item_received",
        description: "The disputed goods or service arrived after all",
        bytes32: "0xafa7760b6eaeb3756917ec71a4add26b6982f123779bbefca4af237ed2a9cbb1"
      ).freeze,
      Reason.new(
        code: "other",
        description: "Other reason",
        bytes32: "0x0c507c226b608fa1f2920608f9c8baf135357fe717c6cd9ac355ae6451b63667"
      ).freeze
    ].freeze

    # Close reasons the protocol records on its own — read back on a dispute, never accepted from a caller.
    SYSTEM = [
      Reason.new(
        code: "full_refund",
        description: "Closed automatically by a full refund",
        bytes32: "0x8d72b2d99f736f70b77d5c4eb77867aa31f7d7be526741b1ba241c1c663b0f6c"
      ).freeze
    ].freeze

    # The lists by kind, for the lookups below.
    KINDS = { open: OPEN, close: CLOSE, system: SYSTEM }.freeze

    # The entries of one kind (:open, :close or :system).
    # @param kind [Symbol, String]
    # @return [Array<Reason>]
    # @raise [ArgumentError] for any other kind.
    def self.all(kind)
      KINDS.fetch(kind.to_sym) { raise ArgumentError, "unknown dispute reason kind: #{kind.inspect}" }
    end

    # The codes of one kind, in dictionary order.
    # @param kind [Symbol, String]
    # @return [Array<String>]
    def self.codes(kind)
      all(kind).map(&:code)
    end

    # The entry of +kind+ that +value+ names — a code ("not_received" or :not_received)
    # or exactly its bytes32 (0x-hex, either case) — or nil. Lookups are per kind
    # because the lists overlap: "other" is both an open and a close reason, with one
    # bytes32.
    # @param kind [Symbol, String]
    # @param value [String, Symbol, nil]
    # @return [Reason, nil]
    def self.find(kind, value)
      return nil if value.nil?

      needle = value.to_s
      all(kind).find { |r| r.code == needle || r.bytes32.casecmp?(needle) }
    end

    # Whether the dispute prepare of +kind+ (:open or :close) would accept +value+.
    # :system is never accepted from a caller, so it always answers false.
    # @param kind [Symbol, String]
    # @param value [String, Symbol, nil]
    # @return [Boolean]
    def self.valid?(kind, value)
      kind.to_sym != :system && !find(kind, value).nil?
    end

    # The description the gateway would give +value+ as a +kind+ reason, or
    # {UNRECOGNISED_DESCRIPTION} when it is not in that list.
    # @param kind [Symbol, String]
    # @param value [String, Symbol, nil]
    # @return [String]
    def self.description_for(kind, value)
      find(kind, value)&.description || UNRECOGNISED_DESCRIPTION
    end
  end
end
