# frozen_string_literal: true
# Code generated by gen/generate.rb — DO NOT EDIT.
# Re-run `ruby gen/generate.rb` after updating the gateway OpenAPI schema.
#
# Source: rail0-gateway/docs/openapi.json
#
# These Structs document the gateway's request/response shapes. They are
# reference only — SDK methods return plain Hashes with symbol keys.

module Rail0
  module Types

    # A wallet's on-chain balances, one entry per chain.
    WalletBalances = Struct.new(
      :wallet_id,  # String
      :address,    # String
      :balances,   # Array
      keyword_init: true
    )

    # Balances on one chain. `native`/`tokens` are null when `error` is present; `error` is null on
    # success.
    ChainBalance = Struct.new(
      :chain_id,      # Integer
      :network_type,  # String
      :native,        # AssetBalance
      :tokens,        # Array
      :error,         # BalanceError
      keyword_init: true
    )

    # A single balance line — the native gas token or one ERC-20.
    AssetBalance = Struct.new(
      :symbol,    # String
      :address,   # Token contract address; null for the native balance.
      :decimals,  # Integer
      :raw,       # String — Balance in base units (exact).
      :amount,    # String — Human-decimal balance.
      keyword_init: true
    )

    # Why a chain's balances couldn't be read.
    BalanceError = Struct.new(
      :code,     # String
      :message,  # String
      keyword_init: true
    )

    # Generic error envelope. `status` is a machine-readable code; additional context fields (e.g.
    # `message`, `resource`, `param`, `errors`, `chain_id`) may also be present.
    ApiErrorBody = Struct.new(
      :status,   # String
      :message,  # String
      keyword_init: true
    )

    Health = Struct.new(
      :status,            # String
      :api_version,       # String
      :contract_version,  # String
      :db,                # String
      :active_chains,     # Integer
      :active_contracts,  # Integer
      :timestamp,         # String
      keyword_init: true
    )

    # A single-use SIWE nonce to embed in the sign-in message.
    Nonce = Struct.new(
      :nonce,       # String — The nonce value to place in the SIWE message's `Nonce:` field.
      :expires_at,  # String — When the nonce expires and can no longer be used.
      keyword_init: true
    )

    # Issued after a successful SIWE verification.
    Session = Struct.new(
      :token,       # String — JWT bearer token.
      :address,     # String — Resolved wallet address.
      :account_id,  # String
      :name,        # String — The account's human-readable name.
      :expires_at,  # String
      keyword_init: true
    )

    # Public blockchain view.
    Blockchain = Struct.new(
      :chain_id,       # Integer
      :name,           # String
      :native_symbol,  # String
      :network_type,   # String
      :explorer_url,   # String
      keyword_init: true
    )

    # Public accepted-token view.
    Token = Struct.new(
      :chain_id,  # Integer
      :symbol,    # String
      :address,   # String
      :decimals,  # Integer
      keyword_init: true
    )

    # Public-safe wallet view (the reduced set a buyer needs to discover a merchant's payment methods).
    Wallet = Struct.new(
      :id,       # String
      :address,  # String
      :label,
      :active,   # Boolean
      keyword_init: true
    )

    # A wallet's token holding, with the wallet, token, and blockchain nested via their own schemas.
    WalletToken = Struct.new(
      :default,     # Boolean
      :active,      # Boolean
      :wallet,      # Wallet
      :token,       # Token
      :blockchain,  # Blockchain
      keyword_init: true
    )

    # A wallet's token holding as nested under its wallet (GET /accounts/:id/wallets): the token plus
    # this wallet's per-token flags, without re-nesting the wallet.
    WalletTokenHolding = Struct.new(
      :token,    # Token
      :active,   # Boolean
      :default,  # Boolean
      keyword_init: true
    )

    # A wallet with its token holdings nested inline. `tokens` is empty when the wallet has none — the
    # wallet is still returned, never omitted.
    WalletWithTokens = Struct.new(
      :id,       # String
      :address,  # String
      :label,
      :active,   # Boolean
      :tokens,   # Array
      keyword_init: true
    )

    # Base persisted payment fields.
    Payment = Struct.new(
      :id,                    # String
      :contract_id,           # String
      :rail0_id,              # String — Protocol-level identifier (66-char hex).
      :status,                # String
      :mode,                  # String
      :amount,                # String
      :capturable_amount,     # String — Mirrors on-chain capturableAmount (escrow still held); base units.
      :refundable_amount,     # String — Mirrors on-chain refundableAmount (held by payee, still refundable); base units.
      :config_hash,           # String
      :payer,                 # String
      :payee,                 # String
      :token,                 # String
      :authorization_expiry,  # Integer
      :refund_expiry,         # Integer
      :disputed,              # Boolean — True while an open dispute exists.
      :last_error_code,       # Decoded reason of the last failed on-chain attempt; null once the payment makes forward progress. Non-null means the latest attempt failed.
      :last_error_message,    # Human-readable form of last_error_code.
      :description,
      :metadata,
      :signed_at,             # When the payer signature was stored (null while unsigned).
      :created_at,            # String
      :updated_at,            # String
      keyword_init: true
    )

    # Buyer-driven, signal-only dispute lifecycle (no fund effect).
    Dispute = Struct.new(
      :id,            # String
      :payment_id,    # String
      :status,        # String
      :reason,        # String — On-chain bytes32 reason code (hex).
      :opened_block,
      :opened_at,     # String
      :closed_by,
      :close_reason,
      :closed_block,
      :closed_at,
      keyword_init: true
    )

    Transaction = Struct.new(
      :id,                    # String
      :payment_id,            # String
      :operation,             # String
      :status,                # String
      :error_code,            # Decoded on-chain failure code (null unless status is "failed"): the RAIL0 custom error in snake_case (e.g. "not_payee"), or "revert" when the selector is unknown. The raw revert bytes are not exposed.
      :error_message,         # Human-readable form of error_code (e.g. "NotPayee"); null unless status is "failed".
      :unsigned_transaction,
      :transaction_hash,
      :amount,
      :block_number,
      :gas_used,              # Gas units used, mirrored from the indexer on confirm.
      :gas_limit,             # Gas limit, mirrored from the indexer on confirm.
      :effective_gas_price,   # Effective gas price in wei, mirrored from the indexer on confirm.
      :base_fee_per_gas,      # Block base fee per gas in wei, mirrored from the indexer on confirm.
      :gas_cost,              # Total gas cost in wei (gas_used * effective_gas_price); derived, null until confirmed.
      :pending_at,
      :submitted_at,
      :confirmed_at,
      :created_at,            # String
      :updated_at,            # String
      keyword_init: true
    )

    Webhook = Struct.new(
      :id,                     # String
      :name,                   # String
      :callback_url,           # String
      :topic,                  # WebhookTopic
      :active,                 # Boolean
      :circuit_state,          # String
      :circuit_failure_count,  # Integer
      :created_at,             # String
      :updated_at,             # String
      keyword_init: true
    )

    EventCallback = Struct.new(
      :id,                # String
      :webhook_id,        # String
      :payment_id,        # String
      :topic,             # String
      :callback_url,      # String
      :response_code,
      :response_message,
      :error_reason,
      :status,            # String
      :created_at,        # String
      :payload,           # The JSON request body POSTed to the callback URL (decompressed).
      keyword_init: true
    )

    # Sweeper view of a stale submitted transaction.
    SyncTransaction = Struct.new(
      :transaction_hash,  # String
      :operation,         # String
      :payment_id,        # String — Protocol-level rail0_id.
      :chain_id,          # Integer
      keyword_init: true
    )

    # Per-chain indexer config.
    SyncBlockchain = Struct.new(
      :chain_id,                # Integer
      :start_block,             # Integer
      :required_confirmations,  # Integer
      :explorer_url,            # Block explorer base URL; null when the chain has none.
      :network_type,            # String — "testnet" or "mainnet"; selects which chains a deployment indexes.
      :rpc_urls,                # Array — Ordered list of public RPC endpoints tried in turn (serial fallback).
      :contracts,               # Array — Active RAIL0 contract addresses on the chain (all watched versions).
      keyword_init: true
    )
  end
end
