# frozen_string_literal: true
# Code generated by gen/generate.rb — DO NOT EDIT.
# Re-run `ruby gen/generate.rb` after updating the schema in rail0-api.
#
# Source: rail0-api/doc/openapi.json

module Rail0
  module Types
    # Primitive type aliases (all are String at runtime)
    # Address       = String  # Checksummed Ethereum address (42 chars, 0x-prefixed)
    # Bytes32       = String  # 32-byte value, hex-encoded (66 chars, 0x-prefixed)
    # Uint256String = String  # uint256 encoded as a decimal string

    # Immutable payment configuration that maps 1-to-1 to the RAIL0 `Payment` Solidity struct.
    PaymentConfig = Struct.new(
      :payer,                # Address — Buyer address. Funds are pulled from this address.
      :payee,                # Address — Merchant address. Authorized to capture, void, and refund.
      :token,                # Address — EIP-3009-capable ERC-20 token address (must be accepted by the RAIL0 deployment).
      :amount,               # Uint256String — Exact amount the payer commits to pay (in token base units).
      :authorizationExpiry,  # Integer — Unix timestamp (seconds). Capture must happen before this; release opens after.
      :refundExpiry,         # Integer — Unix timestamp (seconds). Refund must happen before this. Must be >= authorizationExpiry.
      :feeBps,               # Integer — Fee in basis points (0 = no fee, 10000 = 100%).
      :feeReceiver,          # Address — Recipient of the fee on each capture. Use the zero address when feeBps is 0.
      keyword_init: true
    )

    # EIP-712 domain for the token contract.
    EIP712Domain = Struct.new(
      :name,               # String
      :version,            # String
      :chainId,            # Integer
      :verifyingContract,  # Address — Token contract address.
      keyword_init: true
    )

    # Message fields for the EIP-3009 TransferWithAuthorization signature.
    EIP3009Message = Struct.new(
      :from,         # Address
      :to,           # Address — RAIL0 contract address.
      :value,        # Uint256String
      :validAfter,   # Uint256String — Always '0' for RAIL0 flows.
      :validBefore,  # Uint256String — Equals authorizationExpiry.
      :nonce,        # Bytes32 — keccak256(NONCE_PREFIX, paymentId, configHash). Binds the signature to the exact config and operation type.
      keyword_init: true
    )

    # EIP-712 typed-data structure that the payer must sign. Pass verbatim to `eth_signTypedData_v4`
    # (browser wallets) or compute the hash with any EIP-712 library (backend keys).
    SigningPayload = Struct.new(
      :domain,       # EIP712Domain
      :types,        # Hash
      :primaryType,  # String
      :message,      # EIP3009Message
      keyword_init: true
    )

    # Buyer-supplied payment parameters. Policy fields (authorizationExpiry, refundExpiry, feeBps,
    # feeReceiver) are fixed API configuration applied server-side.
    PaymentInput = Struct.new(
      :payer,   # Address — Buyer address. Funds are pulled from this address.
      :payee,   # Address — Merchant wallet address (walletAddress from GET /accounts/{id}/payment-methods).
      :token,   # Address — ERC-20 token address (tokenAddress from GET /accounts/{id}/payment-methods).
      :amount,  # Uint256String — Amount to pay (in token base units).
      keyword_init: true
    )

    # A single accepted payment method for a merchant: one (chain, token, wallet) combination.
    PaymentMethod = Struct.new(
      :id,             # Integer
      :tokenId,        # Integer
      :chainId,        # Integer
      :chainName,      # String
      :tokenAddress,   # Address — ERC-20 token contract address on the chain.
      :tokenSymbol,    # String
      :tokenDecimals,  # Integer
      :walletAddress,  # Address — Merchant wallet address to use as `payee` in PaymentConfig.
      :isDefault,      # Boolean
      keyword_init: true
    )

    # Parameters needed to create a payment intent.
    CreatePaymentRequest = Struct.new(
      :payment,  # PaymentInput
      :chainId,  # Integer — EVM chain ID of the target network.
      :mode,     # String — `authorize` — funds held in escrow, captured later. `charge` — one-shot: funds immediately distributed. The two modes use different EIP-3009 nonce prefixes; a signature for one cannot be reused for the other.
      keyword_init: true
    )

    CreatePaymentResponse = Struct.new(
      :paymentId,       # Bytes32 — Unique identifier for this payment.
      :configHash,      # Bytes32 — EIP-712 hash of the Payment struct. Commits the signature to the exact payment terms.
      :payment,         # PaymentConfig
      :chainId,         # Integer
      :rail0Contract,   # Address — Address of the RAIL0 contract on the target chain.
      :signingPayload,  # SigningPayload
      keyword_init: true
    )

    # Current state of a payment record. `onChain` is populated when the payment has an active on-chain
    # presence. `lastTxHash`, `failureCode`, and `failureMessage` are present only when relevant.
    GetPaymentResponse = Struct.new(
      :paymentId,            # Bytes32
      :status,               # String — Current lifecycle state. `submitting` = worker enqueued, not yet broadcast. `submitted` = transaction sent to the network, waiting for on-chain confirmation. `failed` is terminal.
      :mode,                 # String
      :amount,               # Uint256String
      :payer,                # Address
      :payee,                # Address
      :token,                # Address
      :chainId,              # Integer
      :authorizationExpiry,  # Integer
      :refundExpiry,         # Integer
      :onChain,              # Hash — Live on-chain amounts. Present when status is authorized, captured, voided, released, charged, or refunded.
      :lastTxHash,           # Bytes32 — Hash of the most recently broadcast transaction. Present once the worker has sent the transaction to the network.
      :failureCode,          # String — Machine-readable failure reason. Present only when status=failed.
      :failureMessage,       # String — Human-readable failure description. Present only when status=failed.
      keyword_init: true
    )

    # An unsigned EIP-1559 transaction ready for the payee to sign. Sign with `eth_signTransaction`
    # (browser wallet) or any secp256k1 library, then submit to `POST
    # /payments/{paymentId}/{operation}`.
    PrepareTransactionResponse = Struct.new(
      :unsignedTransaction,   # String — RLP-encoded unsigned EIP-1559 transaction (type 2).
      :to,                    # Address — Target contract address (informational; already encoded in `unsignedTransaction`).
      :data,                  # String — ABI-encoded calldata (informational).
      :chainId,               # Integer
      :nonce,                 # Integer
      :maxFeePerGas,          # Uint256String
      :maxPriorityFeePerGas,  # Uint256String
      :gasLimit,              # Uint256String
      keyword_init: true
    )

    # Signed transaction to broadcast on-chain. The operation is inferred server-side from the prepare
    # step that was called — the client does not need to specify it.
    SubmitTransactionRequest = Struct.new(
      :signedTransaction,  # String — RLP-encoded signed EIP-1559 transaction as returned by `eth_signTransaction`.
      keyword_init: true
    )

    # Acknowledgement that the transaction has been enqueued. Poll `GET /payments/{paymentId}` for the
    # final outcome.
    SubmitTransactionAcceptedResponse = Struct.new(
      :paymentId,  # Bytes32 — Payment identifier.
      :status,     # String — Always `submitting` — the worker has not yet received the on-chain receipt.
      keyword_init: true
    )

    # Amount to capture from escrow. May be less than `capturableAmount` for a partial capture.
    CapturePaymentRequest = Struct.new(
      :amount,  # Uint256String — Amount to capture (in token base units). Must be > 0 and <= current capturableAmount.
      keyword_init: true
    )

    # Amount to refund to the payer.
    RefundPaymentRequest = Struct.new(
      :amount,  # Uint256String — Amount to refund (in token base units). Must be > 0 and <= current refundableAmount.
      keyword_init: true
    )

    # Optional parameters for the release prepare step.
    ReleaseRequest = Struct.new(
      :callerAddress,  # Address — Address of the account that will sign and submit the release transaction. Defaults to the payment's `payee` if omitted.
      keyword_init: true
    )

    # EIP-712 signature over the `signingPayload` returned by `POST /payments`.
    PayerSignatureRequest = Struct.new(
      :signature,  # String — 65-byte secp256k1 signature (0x-prefixed, 132 chars): r (32 bytes) + s (32 bytes) + v (1 byte).
      keyword_init: true
    )

    PayerSignatureResponse = Struct.new(
      :paymentId,       # Bytes32
      :status,          # String — Confirms the signature was accepted and stored.
      :recoveredPayer,  # Address — The address recovered from the signature — should match `payment.payer`.
      keyword_init: true
    )

    # A blockchain transaction associated with a payment. A `submitted` row is pre-created as soon as
    # the transaction is broadcast on-chain, so Ponder (the event indexer) can reconcile by `txHash` and
    # update the row to `confirmed` or `failed` once the block is mined.
    Transaction = Struct.new(
      :txHash,       # Bytes32 — Keccak256 hash of the broadcast transaction. Globally unique; used as the Ponder reconciliation key.
      :paymentId,    # Bytes32 — Parent payment identifier.
      :operation,    # String — Smart contract operation executed by this transaction.
      :status,       # String — `submitted` = transaction broadcast to the network, awaiting on-chain confirmation. `confirmed` = mined and successful. `failed` = transaction reverted on-chain.
      :amount,       # Uint256String — Token amount processed. `null` until confirmed.
      :feeAmount,    # Uint256String — Protocol fee deducted. `"0"` until confirmed.
      :blockNumber,  # Integer — Block number in which the transaction was mined. `null` until confirmed.
      :submittedAt,  # String — ISO 8601 timestamp when the transaction was broadcast on-chain.
      :confirmedAt,  # String — ISO 8601 timestamp when the transaction was confirmed. `null` until confirmed.
      keyword_init: true
    )

    ApiErrorBody = Struct.new(
      :error,    # String — Machine-readable error code (snake_case).
      :message,  # String — Human-readable error description.
      keyword_init: true
    )
  end
end
